puts "Creating users"
User.create(name: 'Charlie', age: 26, username: 'CandyCaneJoe', password: 'p', password_confirmation: 'p', bio: 'Just do it.')
User.create(name: 'Sean', age: 24, username: 'SirLogan', password: 'p', password_confirmation: 'p', bio: 'Just an animal looking for a home.')
User.create(name: 'Daniel', age: 25, username: 'Daniel', password: 'p', password_confirmation: 'p', bio: 'Big D jus chillen\'')
puts "Created users"

puts "Creating locations"
Location.create(neighborhood: 'Battery Park City')
Location.create(neighborhood: 'Bowery')
Location.create(neighborhood: 'Carnegie Hill')
Location.create(neighborhood: 'Central Park')
Location.create(neighborhood: 'Chelsea')
Location.create(neighborhood: 'Chinatown')
Location.create(neighborhood: 'Civic Center')
Location.create(neighborhood: 'East Harlem')
Location.create(neighborhood: 'Financial District')
Location.create(neighborhood: 'Flatiron')
Location.create(neighborhood: 'Garment District')
Location.create(neighborhood: 'Gramercy Park')
Location.create(neighborhood: 'Greenwich Village')
Location.create(neighborhood: 'East Village')
Location.create(neighborhood: 'West Village')
Location.create(neighborhood: 'Hamilton Heights')
Location.create(neighborhood: 'Harlem')
Location.create(neighborhood: 'Hell\'s Kitchen / Clinton')
Location.create(neighborhood: 'Inwood')
Location.create(neighborhood: 'Kips Bay')
Location.create(neighborhood: 'Lenox Hill')
Location.create(neighborhood: 'Little Italy')
Location.create(neighborhood: 'Lower Eastside')
Location.create(neighborhood: 'Madison Square')
Location.create(neighborhood: 'Manhattan Valley')
Location.create(neighborhood: 'Meatpacking District')
Location.create(neighborhood: 'Midtown')
Location.create(neighborhood: 'Morningside Heights')
Location.create(neighborhood: 'Murray Hill')
Location.create(neighborhood: 'NoHo')
Location.create(neighborhood: 'NoLita')
Location.create(neighborhood: 'Roosevelt Island')
Location.create(neighborhood: 'SoHo')
Location.create(neighborhood: 'Stuyvesant Town (Stuyvesant Square)')
Location.create(neighborhood: 'Sutton Place')
Location.create(neighborhood: 'Times Square')
Location.create(neighborhood: 'Tribeca')
Location.create(neighborhood: 'Turtle Bay')
Location.create(neighborhood: 'Upper Eastside')
Location.create(neighborhood: 'Upper Westside')
Location.create(neighborhood: 'Washington Heights')
Location.create(neighborhood: 'Yorkville')
puts "Created locations"

puts "Creating stories"
Story.create(title: 'Hamburger Squirrel', content: 'Saw a hamburger eating a squirrel.', user_id: 1, location_id: 2)
Story.create(title: 'Sick Woman on Subway', content: 'She was sick. People helped her and then went on with their days.', user_id: 2, location_id: 1)
Story.create(title: 'Peed a Lot Today.', content: 'I peed three times already today.', user_id: 3, location_id: 5)
Story.create(title: 'UES Shenanigans.', content: 'Saw a dog that was wearing a gucci collar and a Louis Vuitton leash. Totally clashed - So embarrising.', user_id: 1, location_id: 2)
Story.create(title: 'Lorem Ipsum.', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', user_id: 2, location_id: 1)
Story.create(title: 'Lorem 2', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', user_id: 2, location_id: 3)
Story.create(title: 'What Happens Next Will SHOCK You...', content: 'I went to duane reade. Pretty chill day.', user_id: 3, location_id: 2)
puts "Created stories"

puts 'Creating tags'
Tag.create(tag_name: 'Funny')
Tag.create(tag_name: 'Sad')
Tag.create(tag_name: 'Cute')
Tag.create(tag_name: 'Gross')
Tag.create(tag_name: 'Scary')
Tag.create(tag_name: 'Shocking')
Tag.create(tag_name: 'Happy')
puts 'Created tags'

puts 'Creating storytags'
StoryTag.create(tag_id: 2, story_id: 1)
StoryTag.create(tag_id: 5, story_id: 1)
StoryTag.create(tag_id: 6, story_id: 1)
StoryTag.create(tag_id: 3, story_id: 2)
StoryTag.create(tag_id: 2, story_id: 2)
StoryTag.create(tag_id: 2, story_id: 3)
StoryTag.create(tag_id: 7, story_id: 3)
StoryTag.create(tag_id: 7, story_id: 4)
StoryTag.create(tag_id: 7, story_id: 5)
StoryTag.create(tag_id: 7, story_id: 6)
StoryTag.create(tag_id: 7, story_id: 7)
StoryTag.create(tag_id: 4, story_id: 7)
puts 'Created storytags'
