puts "Creating users"
User.create(name: 'Charlie', age: 26, username: 'CandyCaneJoe', password: 'p', password_confirmation: 'p', bio: 'Just do it.')
User.create(name: 'Sean', age: 24, username: 'SirLogan', password: 'p', password_confirmation: 'p', bio: 'Just an animal looking for a home.')
User.create(name: 'Daniel', age: 25, username: 'deejay', password: 'p', password_confirmation: 'p', bio: 'Hi my name is Daniel and I like to write stories about what is happening in my neighborhoods.\'')
User.create(name: 'Mike', age: 20, username: 'Big_boi_mike', password: 'p', password_confirmation: 'p', bio: 'They call me big mike.')
User.create(name: 'Joe', age: 39, username: 'Average_Joe', password: 'p', password_confirmation: 'p', bio: 'Im just the average joe.')
User.create(name: 'Jacob', age: 14, username: 'Young1', password: 'p', password_confirmation: 'p', bio: 'Not too young to write stories')
puts "Created users"

puts "Creating locations"
Location.create(neighborhood: 'Battery Park City')
Location.create(neighborhood: 'Bowery')
Location.create(neighborhood: 'Carnegie Hill')
Location.create(neighborhood: 'Central Park')
Location.create(neighborhood: 'Chelsea')
Location.create(neighborhood: 'Chinatown')
Location.create(neighborhood: 'Civic Center')
Location.create(neighborhood: 'East Harlem')
Location.create(neighborhood: 'Financial District')
Location.create(neighborhood: 'Flatiron')
Location.create(neighborhood: 'Garment District')
Location.create(neighborhood: 'Gramercy Park')
Location.create(neighborhood: 'Greenwich Village')
Location.create(neighborhood: 'East Village')
Location.create(neighborhood: 'West Village')
Location.create(neighborhood: 'Hamilton Heights')
Location.create(neighborhood: 'Harlem')
Location.create(neighborhood: 'Hell\'s Kitchen / Clinton')
Location.create(neighborhood: 'Inwood')
Location.create(neighborhood: 'Kips Bay')
Location.create(neighborhood: 'Lenox Hill')
Location.create(neighborhood: 'Little Italy')
Location.create(neighborhood: 'Lower Eastside')
Location.create(neighborhood: 'Madison Square')
Location.create(neighborhood: 'Manhattan Valley')
Location.create(neighborhood: 'Meatpacking District')
Location.create(neighborhood: 'Midtown')
Location.create(neighborhood: 'Morningside Heights')
Location.create(neighborhood: 'Murray Hill')
Location.create(neighborhood: 'NoHo')
Location.create(neighborhood: 'NoLita')
Location.create(neighborhood: 'Roosevelt Island')
Location.create(neighborhood: 'SoHo')
Location.create(neighborhood: 'Stuyvesant Town (Stuyvesant Square)')
Location.create(neighborhood: 'Sutton Place')
Location.create(neighborhood: 'Times Square')
Location.create(neighborhood: 'Tribeca')
Location.create(neighborhood: 'Turtle Bay')
Location.create(neighborhood: 'Upper Eastside')
Location.create(neighborhood: 'Upper Westside')
Location.create(neighborhood: 'Washington Heights')
Location.create(neighborhood: 'Yorkville')
puts "Created locations"

puts "Creating stories"
Story.create(title: 'Hamburger Squirrel', content: 'Saw a hamburger eating a squirrel.', user_id: 1, location_id: 1)
Story.create(title: 'Sick Woman on Subway', content: 'She was sick. People helped her and then went on with their days.', user_id: 2, location_id: 2)
Story.create(title: 'Drank too much coffee', content: 'I drank too much coffee and had t.o use the bathroom 12 times today.', user_id: 3, location_id: 3)
Story.create(title: 'UES Shenanigans.', content: 'Saw a dog that was wearing a gucci collar and a Louis Vuitton leash. Totally clashed - So embarrising.', user_id: 4, location_id: 4)
Story.create(title: 'Lorem Ipsum.', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', user_id: 5, location_id: 4)
Story.create(title: 'Lorem 2', content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mi', user_id: 2, location_id: 3)
Story.create(title: 'What Happens Next Will SHOCK You...', content: 'I went to duane reade. Pretty chill day.', user_id: 1, location_id: 5)
Story.create(title: 'Robbery Story', content: 'It’s the rare story concerning a robbery that ends up being so incredibly sweet. Like its name suggests, “The Grid” perfectly captures that which connects all New Yorkers. In this case, though, “The Grid” is not the tyrannical behemoth known as Time Warner Cable, but instead a map of all the first kisses happening across the city.', user_id: 2, location_id: 6)
Story.create(title: 'Private detectives in the city', content: 'If you can stomach it, try to put the ickiness aside and enjoy this unexpectedly light, silly New Yorker piece about a private detective’s sting on a prostitution ring made up of college women who are paid to do nothing but entertain the literary fancies of men by engaging with them in intellectual jabber.', user_id: 3, location_id: 7)
Story.create(title: 'Dog walking downtown', content: 'Taking on the streets. East or Westside. Uptown and Down. The pace quickens through the boroughs from necessity. Every move the most important. Too much competition. Looking at each other for someone to blame. Doing anything just to be part of the magnitude. Everybody lost in the expanse.', user_id: 5, location_id: 8)
Story.create(title: 'New Neighborhoods', content: 'Welcome to Have a NYC, the first of a New York short stories series, edited by Peter Carlaftes and Kat Georges. In Have a NYC, Three Rooms Press aims to acknowlege that the energy that drives New York is still there, and not just in “hipster” neighborhoods or well-trodden streets. The stories are forming and reforming moment by moment. Drifters pass through and lend their ideas; natives look to cling to the things they see are ebbing away; the underbelly still writhes and reels to an urban beat; and the familiar landmarks take on new looks and menace as technology slowly grips the throngs of people walking the New York City streets. Authors include: Claus Ankersen, Larissa Shmailo, Adam R. Burnett, Darlene Cah, David R. Lincoln, Lawrence Block, Kofi Fosu Forson, Pedro Ponce, Ronald H. Bass, Jane Ormerod, Peter D. Marra, Puma Perl, Lisa Ferber, Keven Dupzyk and Janet Hamill.', user_id: 5, location_id: 9)
Story.create(title: 'Places and reads', content: 'Riveting tales of the underbelly of modern-day New York City hook-up with hilarious and poignant stories of love and loss in Have A NYC 3 an annual collection of engaging short stories. This edition, edited by Peter Carlaftes and Kat Georges, includes eighteen urban tales that merge familiar landscapes with a plethora of unusual characters, ready for a thrill–or a kill!–as they pass through the streets and homes of New York City’s ever-vibrant boroughs. Authors in this edtion include acclaimed crime writer Lawrence Block (Eight Million Ways to Die.', user_id: 1, location_id: 10)
Story.create(title: 'Taking a walk at night', content: 'It was a beautiful summer day in New York City. It was a day made for walking. John was standing at an intersection near the Brooklyn Bridge. He had driven over the bridge before. But he had never walked over the bridge. He started walking uphill on the pedestrian path. Many people were walking ahead of him. Many people were also walking toward him', user_id: 2, location_id: 11)
Story.create(title: 'The history of the Sonics', content: 'Its been 10 years now since the Sonics left Seattle and took the supernova that Durant was to become and the lottery pick that turned into Russell Westbrook with them', user_id: 3, location_id: 12)
Story.create(title: 'Crazy Happenings In the City', content: 'It was a warm, sunny day in Manhattan. Many people were standing in a long line. They had bought tickets for the Statue of Liberty. They were waiting to board the boat. Neil could see the statue in the distance. It looked pretty small. He bought a ticket. Now all he needed was a hat. A sidewalk vendor nearby was selling baseball caps', user_id: 4, location_id: 13)
Story.create(title: 'The worst day of my life', content: 'Streets and subways—even the sidewalks!—are jam‐packed. And the bikers—just yesterday a biker almost ran me over. They come at you from everywhere—from the front, from the back, and from the sides. When I step into the street, I look out for bikers first, cars second.', user_id: 5, location_id: 14)
Story.create(title: 'Why I dont eat tacos anymore', content: 'I went to duane reade. Pretty chill day.', user_id: 1, location_id: 15)
Story.create(title: 'The best day of my life.', content: 'The waitress showed them to their table. It wasn’t where they had sat the previous month. That table was quiet and almost private. This table, at the south end of the restaurant, was only five feet away from a busy cash register. Also, the table was at the intersection of two aisles. One aisle led to another dining room. One aisle led straight to the buffet line. The foot traffic was constant throughout their meal.', user_id: 2, location_id: 16)
Story.create(title: 'Enjoying a nice day', content: 'Joe first walked by the man at 2 p.m. The man was standing in the middle of a busy sidewalk in Koreatown. He was bent over, face down. Joe could see only the top and back of the man’s head. His hands were moving slowly near his knees. At about 3 p.m., Joe returned from his errands. The man was still on the sidewalk. He was in the same spot. Joe decided to stop. He stood nearby and watched the man. The man wasn’t making a sound. He just stood there, bent over, face down. He seemed to be looking at his hands. His hands continued to move slowly in front of his knees. This man needs help, Joe thought. ', user_id: 3, location_id: 17)
Story.create(title: 'Things to do in October', content: 'Joe first walked by the man at 2 p.m. The man was standing in the middle of a busy sidewalk in Koreatown. He was bent over, face down. Joe could see only the top and back of the man’s head. His hands were moving slowly near his knees. At about 3 p.m., Joe returned from his errands. The man was still on the sidewalk. He was in the same spot. Joe decided to stop. He stood nearby and watched the man. The man wasn’t making a sound. He just stood there, bent over, face down. He seemed to be looking at his hands. His hands continued to move slowly in front of his knees. This man needs help, Joe thought. ', user_id: 4, location_id: 17)
Story.create(title: 'Things to do after work', content: 'The waitress showed them to their table. It wasn’t where they had sat the previous month. That table was quiet and almost private. This table, at the south end of the restaurant, was only five feet away from a busy cash register. Also, the table was at the intersection of two aisles. One aisle led to another dining room. One aisle led straight to the buffet line. The foot traffic was constant throughout their meal.', user_id: 5, location_id: 1)
Story.create(title: 'After school special.', content: 'I went to duane reade. Pretty chill day.', user_id: 5, location_id: 5)
Story.create(title: 'This was insane', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 7)
Story.create(title: 'What is up people', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 4, location_id: 10)
Story.create(title: 'National history', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 4, location_id: 12)
Story.create(title: 'Going to museums', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 12)
Story.create(title: 'My favorite place', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 15)
Story.create(title: 'Places to eat', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 1)
Story.create(title: 'Eating late night', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 25)
Story.create(title: 'Staying up late', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 20)
Story.create(title: 'Waking up early.', content: 'He is psychologically experienced in thinking of Blackwell’s Island, the local jail, as a de facto winter homeless shelter, and the narrative shows him developing a series of tactics intended to encourage the police to classify him as a criminal and arrest him.', user_id: 5, location_id: 23)
Story.create(title: 'Everything In Between', content: 'The waitress showed them to their table. It wasn’t where they had sat the previous month. That table was quiet and almost private. This table, at the south end of the restaurant, was only five feet away from a busy cash register. Also, the table was at the intersection of two aisles. One aisle led to another dining room. One aisle led straight to the buffet line. The foot traffic was constant throughout their meal.', user_id: 5, location_id: 35)
Story.create(title: 'Lets goooo', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 34)
Story.create(title: 'Storytime with Dan', content: 'The N train stopped at the 23rd Street subway station. A young woman got on the train. She stood next to Doug. Doug didn’t offer her his seat. The train pulled out of the station. The woman suddenly started talking loudly and slowly.', user_id: 5, location_id: 33)
Story.create(title: 'Lets goooooooooooooooooo', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 32)
Story.create(title: 'Best title', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 20)
Story.create(title: 'Not a good story', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 21)
Story.create(title: 'My first story', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 5, location_id: 19)
Story.create(title: 'Listen to this', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 3, location_id: 2)
Story.create(title: 'This is my story', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 1, location_id: 37)
Story.create(title: 'Imagine this happening...', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 2, location_id: 2)
Story.create(title: 'What is going on people', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 3, location_id: 12)
Story.create(title: 'Doing things that make things', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 4, location_id: 16)
Story.create(title: 'Doing crazy things with crazy people', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 6, location_id: 41)
Story.create(title: 'What is happening today', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 6, location_id: 41)
Story.create(title: 'Weekend warrior', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 6, location_id: 40)
Story.create(title: 'Im getting lit... boi', content: 'The story is set in New York City in the year 1920, 25 years after the story’s publication. It is told from the view of Hildred Castaigne, a young man whose personality changes drastically following a head injury sustained by falling from his horse. He is subsequently committed to an asylum for treatment of insanity by Dr. Archer. Due to his accident, Hildred is a prime example of an unreliable narrator.', user_id: 6, location_id: 39)
puts "Created stories"

puts 'Creating tags'
Tag.create(tag_name: 'Funny')
Tag.create(tag_name: 'Sad')
Tag.create(tag_name: 'Cute')
Tag.create(tag_name: 'Gross')
Tag.create(tag_name: 'Scary')
Tag.create(tag_name: 'Shocking')
Tag.create(tag_name: 'Happy')
Tag.create(tag_name: 'Romantic')
Tag.create(tag_name: 'Personal')
Tag.create(tag_name: 'Professional')
Tag.create(tag_name: 'MTA')
Tag.create(tag_name: 'Park')
Tag.create(tag_name: 'Nightlife')
Tag.create(tag_name: 'Daytime')
Tag.create(tag_name: 'School')
Tag.create(tag_name: 'Wildcard')
puts 'Created tags'

puts 'Creating storytags'
StoryTag.create(tag_id: 2, story_id: 1)
StoryTag.create(tag_id: 5, story_id: 1)
StoryTag.create(tag_id: 6, story_id: 1)
StoryTag.create(tag_id: 3, story_id: 2)
StoryTag.create(tag_id: 2, story_id: 2)
StoryTag.create(tag_id: 2, story_id: 3)
StoryTag.create(tag_id: 7, story_id: 3)
StoryTag.create(tag_id: 11, story_id: 4)
StoryTag.create(tag_id: 12, story_id: 5)
StoryTag.create(tag_id: 7, story_id: 6)
StoryTag.create(tag_id: 13, story_id: 7)
StoryTag.create(tag_id: 1, story_id: 8)
StoryTag.create(tag_id: 2, story_id: 9)
StoryTag.create(tag_id: 3, story_id: 10)
StoryTag.create(tag_id: 4, story_id: 11)
StoryTag.create(tag_id: 10, story_id: 12)
StoryTag.create(tag_id: 6, story_id: 13)
StoryTag.create(tag_id: 8, story_id: 14)
StoryTag.create(tag_id: 1, story_id: 15)
StoryTag.create(tag_id: 2, story_id: 16)
StoryTag.create(tag_id: 3, story_id: 17)
StoryTag.create(tag_id: 9, story_id: 18)
StoryTag.create(tag_id: 5, story_id: 19)
StoryTag.create(tag_id: 6, story_id: 20)
StoryTag.create(tag_id: 7, story_id: 21)
StoryTag.create(tag_id: 1, story_id: 22)
StoryTag.create(tag_id: 2, story_id: 23)
StoryTag.create(tag_id: 3, story_id: 24)
StoryTag.create(tag_id: 3, story_id: 25)
StoryTag.create(tag_id: 4, story_id: 26)
StoryTag.create(tag_id: 5, story_id: 27)
StoryTag.create(tag_id: 6, story_id: 28)
StoryTag.create(tag_id: 9, story_id: 29)
StoryTag.create(tag_id: 2, story_id: 30)
StoryTag.create(tag_id: 1, story_id: 31)
StoryTag.create(tag_id: 8, story_id: 32)
StoryTag.create(tag_id: 3, story_id: 33)
StoryTag.create(tag_id: 4, story_id: 34)
StoryTag.create(tag_id: 5, story_id: 35)
StoryTag.create(tag_id: 6, story_id: 36)
StoryTag.create(tag_id: 7, story_id: 37)
StoryTag.create(tag_id: 1, story_id: 38)
StoryTag.create(tag_id: 2, story_id: 39)
StoryTag.create(tag_id: 14, story_id: 40)
StoryTag.create(tag_id: 4, story_id: 41)
StoryTag.create(tag_id: 5, story_id: 42)
StoryTag.create(tag_id: 6, story_id: 43)
StoryTag.create(tag_id: 12, story_id: 44)
StoryTag.create(tag_id: 1, story_id: 45)
StoryTag.create(tag_id: 2, story_id: 46)
StoryTag.create(tag_id: 3, story_id: 44)
StoryTag.create(tag_id: 4, story_id: 43)
StoryTag.create(tag_id: 5, story_id: 42)
StoryTag.create(tag_id: 12, story_id: 1)
StoryTag.create(tag_id: 7, story_id: 2)
StoryTag.create(tag_id: 2, story_id: 3)
StoryTag.create(tag_id: 13, story_id: 4)
StoryTag.create(tag_id: 1, story_id: 12)
StoryTag.create(tag_id: 3, story_id: 20)
StoryTag.create(tag_id: 4, story_id: 22)
StoryTag.create(tag_id: 5, story_id: 21)
StoryTag.create(tag_id: 12, story_id: 11)
StoryTag.create(tag_id: 7, story_id: 9)
StoryTag.create(tag_id: 1, story_id: 8)
StoryTag.create(tag_id: 2, story_id: 10)
StoryTag.create(tag_id: 3, story_id: 32)
StoryTag.create(tag_id: 2, story_id: 31)
StoryTag.create(tag_id: 5, story_id: 37)
StoryTag.create(tag_id: 6, story_id: 38)
StoryTag.create(tag_id: 14, story_id: 41)
StoryTag.create(tag_id: 11, story_id: 42)
StoryTag.create(tag_id: 12, story_id: 18)
StoryTag.create(tag_id: 3, story_id: 12)
StoryTag.create(tag_id: 15, story_id: 11)
StoryTag.create(tag_id: 5, story_id: 7)
StoryTag.create(tag_id: 6, story_id: 6)
StoryTag.create(tag_id: 7, story_id: 8)
StoryTag.create(tag_id: 16, story_id: 5)
StoryTag.create(tag_id: 4, story_id: 2)
StoryTag.create(tag_id: 6, story_id: 22)
StoryTag.create(tag_id: 13, story_id: 28)
StoryTag.create(tag_id: 16, story_id: 29)
StoryTag.create(tag_id: 10, story_id: 31)
StoryTag.create(tag_id: 5, story_id: 32)
StoryTag.create(tag_id: 12, story_id: 33)
StoryTag.create(tag_id: 7, story_id: 41)
StoryTag.create(tag_id: 2, story_id: 42)
StoryTag.create(tag_id: 15, story_id: 40)
StoryTag.create(tag_id: 10, story_id: 48)
puts 'Created storytags'

puts 'Creating comments'
Comment.create(content: "YO", story_id: 1, user_id: 1)
Comment.create(content: "YO", story_id: 2, user_id: 2)
Comment.create(content: "YO", story_id: 3, user_id: 3)
Comment.create(content: "YO", story_id: 4, user_id: 4)
Comment.create(content: "YO", story_id: 5, user_id: 5)
Comment.create(content: "YO", story_id: 6, user_id: 6)
Comment.create(content: "YO", story_id: 7, user_id: 1)
Comment.create(content: "YO", story_id: 8, user_id: 2)
Comment.create(content: "YO", story_id: 9, user_id: 3)
Comment.create(content: "YO", story_id: 10, user_id: 4)
Comment.create(content: "YO", story_id: 11, user_id: 5)
Comment.create(content: "YO", story_id: 12, user_id: 6)
Comment.create(content: "YO", story_id: 13, user_id: 1)
Comment.create(content: "YO", story_id: 14, user_id: 2)
Comment.create(content: "YO", story_id: 15, user_id: 3)
Comment.create(content: "YO", story_id: 16, user_id: 4)
Comment.create(content: "YO", story_id: 17, user_id: 5)
Comment.create(content: "YO", story_id: 18, user_id: 6)
Comment.create(content: "YO", story_id: 14, user_id: 2)
Comment.create(content: "YO", story_id: 15, user_id: 3)
Comment.create(content: "YO", story_id: 16, user_id: 4)
Comment.create(content: "YO", story_id: 17, user_id: 5)
Comment.create(content: "YO", story_id: 18, user_id: 6)
Comment.create(content: "YO", story_id: 19, user_id: 2)
Comment.create(content: "YO", story_id: 20, user_id: 3)
Comment.create(content: "YO", story_id: 21, user_id: 4)
Comment.create(content: "YO", story_id: 22, user_id: 5)
Comment.create(content: "YO", story_id: 23, user_id: 6)
Comment.create(content: "YO", story_id: 24, user_id: 2)
Comment.create(content: "YO", story_id: 25, user_id: 3)
Comment.create(content: "YO", story_id: 26, user_id: 4)
Comment.create(content: "YO", story_id: 27, user_id: 5)
Comment.create(content: "YO", story_id: 28, user_id: 6)
Comment.create(content: "YO", story_id: 29, user_id: 2)
Comment.create(content: "YO", story_id: 30, user_id: 3)
Comment.create(content: "YO", story_id: 31, user_id: 4)
Comment.create(content: "YO", story_id: 32, user_id: 5)
Comment.create(content: "YO", story_id: 33, user_id: 6)
Comment.create(content: "YO", story_id: 18, user_id: 6)
Comment.create(content: "YO", story_id: 19, user_id: 2)
Comment.create(content: "YO", story_id: 20, user_id: 3)
Comment.create(content: "YO", story_id: 21, user_id: 4)
Comment.create(content: "YO", story_id: 22, user_id: 5)
Comment.create(content: "YO", story_id: 23, user_id: 6)
Comment.create(content: "YO", story_id: 24, user_id: 2)
Comment.create(content: "YO", story_id: 25, user_id: 3)
Comment.create(content: "YO", story_id: 26, user_id: 4)
Comment.create(content: "YO", story_id: 27, user_id: 5)
Comment.create(content: "YO", story_id: 28, user_id: 6)
Comment.create(content: "YO", story_id: 29, user_id: 2)
Comment.create(content: "YO", story_id: 30, user_id: 3)
Comment.create(content: "YO", story_id: 31, user_id: 4)
Comment.create(content: "YO", story_id: 32, user_id: 5)
Comment.create(content: "YO", story_id: 33, user_id: 6)
Comment.create(content: "YO", story_id: 18, user_id: 6)
Comment.create(content: "YO", story_id: 19, user_id: 2)
Comment.create(content: "YO", story_id: 20, user_id: 3)
Comment.create(content: "YO", story_id: 21, user_id: 4)
Comment.create(content: "YO", story_id: 22, user_id: 5)
Comment.create(content: "YO", story_id: 23, user_id: 6)
Comment.create(content: "YO", story_id: 24, user_id: 2)
Comment.create(content: "YO", story_id: 25, user_id: 3)
Comment.create(content: "YO", story_id: 26, user_id: 4)
Comment.create(content: "YO", story_id: 27, user_id: 5)
Comment.create(content: "YO", story_id: 28, user_id: 6)
Comment.create(content: "YO", story_id: 29, user_id: 2)
Comment.create(content: "YO", story_id: 30, user_id: 3)
Comment.create(content: "YO", story_id: 31, user_id: 4)
Comment.create(content: "YO", story_id: 32, user_id: 5)
Comment.create(content: "YO", story_id: 33, user_id: 6)
Comment.create(content: "YO", story_id: 34, user_id: 6)
Comment.create(content: "YO", story_id: 35, user_id: 2)
Comment.create(content: "YO", story_id: 36, user_id: 3)
Comment.create(content: "YO", story_id: 37, user_id: 4)
Comment.create(content: "YO", story_id: 38, user_id: 5)
Comment.create(content: "YO", story_id: 39, user_id: 6)
Comment.create(content: "YO", story_id: 41, user_id: 2)
Comment.create(content: "YO", story_id: 40, user_id: 3)
Comment.create(content: "YO", story_id: 42, user_id: 4)
Comment.create(content: "YO", story_id: 30, user_id: 5)
Comment.create(content: "YO", story_id: 31, user_id: 6)
Comment.create(content: "YO", story_id: 32, user_id: 2)
Comment.create(content: "YO", story_id: 30, user_id: 3)
Comment.create(content: "YO", story_id: 29, user_id: 4)
Comment.create(content: "YO", story_id: 28, user_id: 5)
Comment.create(content: "YO", story_id: 27, user_id: 6)
Comment.create(content: "YO", story_id: 33, user_id: 6)
Comment.create(content: "YO", story_id: 34, user_id: 6)
Comment.create(content: "YO", story_id: 35, user_id: 2)
Comment.create(content: "YO", story_id: 36, user_id: 3)
Comment.create(content: "YO", story_id: 37, user_id: 4)
Comment.create(content: "YO", story_id: 38, user_id: 5)
Comment.create(content: "YO", story_id: 39, user_id: 6)
Comment.create(content: "YO", story_id: 41, user_id: 2)
Comment.create(content: "YO", story_id: 40, user_id: 3)
Comment.create(content: "YO", story_id: 42, user_id: 4)
Comment.create(content: "YO", story_id: 30, user_id: 5)
Comment.create(content: "YO", story_id: 31, user_id: 6)
Comment.create(content: "YO", story_id: 29, user_id: 2)
Comment.create(content: "YO", story_id: 26, user_id: 3)
Comment.create(content: "YO", story_id: 23, user_id: 4)
Comment.create(content: "YO", story_id: 22, user_id: 5)
Comment.create(content: "YO", story_id: 21, user_id: 6)
Comment.create(content: "YO", story_id: 20, user_id: 6)
Comment.create(content: "YO", story_id: 34, user_id: 6)
Comment.create(content: "YO", story_id: 35, user_id: 2)
Comment.create(content: "YO", story_id: 36, user_id: 3)
Comment.create(content: "YO", story_id: 18, user_id: 4)
Comment.create(content: "YO", story_id: 19, user_id: 5)
Comment.create(content: "YO", story_id: 17, user_id: 6)
Comment.create(content: "YO", story_id: 14, user_id: 2)
Comment.create(content: "YO", story_id: 15, user_id: 3)
Comment.create(content: "YO", story_id: 13, user_id: 4)
Comment.create(content: "YO", story_id: 30, user_id: 5)
Comment.create(content: "YO", story_id: 12, user_id: 6)
Comment.create(content: "YO", story_id: 10, user_id: 2)
Comment.create(content: "YO", story_id: 11, user_id: 3)
Comment.create(content: "YO", story_id: 29, user_id: 4)
Comment.create(content: "YO", story_id: 12, user_id: 5)
Comment.create(content: "YO", story_id: 27, user_id: 6)
puts 'Created comments'
